redis:
    image: redis:latest
    ports:
      - "6479:6379"

mongo:
    image: mongo:3.2
    ports:
      - "27018:27017"

php:
    build: php
    volumes:
      - ./code:/var/www
    links:
      - redis
      - mongo

web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./code:/var/www
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
      - mongo